server:
  port: 8006
  
spring:
  application:
    name: zuul-service

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8000/eureka/
      
zuul:
  routes:
    helloService:
      path: /hello-service/**
      serviceId: hello-service
    hiService:
      path: /hi-service/**
      serviceId: hi-service

hello-service:
  ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 5000
    
hi-service:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 500
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000