server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

spring:
  application:
    name: hi-service
  #Zipkin 服务端的地址
  zipkin:
    base-url: http://localhost:9411
  #Sleuth 数据采集百分比，默认0.1，即10%的调用情况被收集，这里调成50%
  sleuth:
    sampler:
      probability: 0.5
